version: '3'

services:
  
  client:
    build: client
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - ./client:/app
      - /app/node_modules

  server:
    build: server
    ports:
      - 5000:5000
    volumes:
      - ./server:/app

  db:
    image: mongo:latest
    ports:
      - 27017:27017
      - 27018:27018
      - 27019:27019
    volumes:
      - ./scripts:/scripts
      - ./data/db:/data/db
